### ISSUE TITLE
feat: add ability to set polling interval

### ISSUE THREAD

**Issue by kickouille** [laszlojakab/homeassistant-easycontrols#15]
Hello,

First of all thank you for your component which works great.

This issue is more of a feature request than a real problem. I noticed that on some sensors if not all, states are update every minutes, which I find pretty aggressive, and would like to extend to 5 minutes for example.
Indeed, there are a lot of sensors and over time that creates a lot of data to store.

I am not experienced in coding HA components, went over the code and could not find what determines the polling interval. If so I could have tried to do a pull request...

An option on the integration to be able to set this interval would be great. Do you think it is feasible?

Regards,

Yanik

**Comment by laszlojakab** [comment]
Hello Yanik,

Polling interval default value set by Home Assistant. It is 30 seconds for sensors:

https://github.com/home-assistant/core/blob/eda9291ca1ec966c7a5855db8bcd816baf01866c/homeassistant/components/sensor/__init__.py#L69

I would suggest to disable entities which you don't need (for example you can disable preheater and after heater sensors if they are not installed for you). Another thing you can do to reduce amount of stored data to disable recorder for entities you don't need or not relevant (in that case these entities won't have a history!):

https://www.home-assistant.io/integrations/recorder/

For example you can probably disable recorder for operation hours (I think it is only important to know the current value not the history for them). If you need history for temperatures and only want to store it every five minute I would suggest to create statistics sensor for them and only record these sensor values:

https://www.home-assistant.io/integrations/statistics/

With disabling entities and fine tuning recorder you can highly customize the amount of data that you store. I think that should be the way to solve 'too much data' problem. Is this solution faisable for you?

**Comment by kickouille** [comment]
Hi Laszlo,

Thank you for your explanation, and all your recommendations totally make sense.
However, aster opening this issue, I also realized that my Home Assistant performances drastically went down while the module was operating. I'm running it on a Raspberry Pi 3, and this is maybe a bit light.
If I disable entities, will your module still poll related modbus objects?
In the meatime, I went back to helios2mqtt which is obviously less cool in HA context, but at least I can fine tune which object I want to poll and when, and run on the same Pi.

Best regards,

Yanik

**Comment by laszlojakab** [comment]
Hello Yanik,

Ok, so the real problem is performance. I'm also running my HA on RPI 3B+. I also noticed it is a bit slower when integration runs. There is a special way how Helios handles modbus protocol, you can read more about it here: https://github.com/baradi09/eazyctrl#notes-on-concurrent-access-conflicts
In short: you can only query one variable in any given moment, you can't do paralel request to the same device. At the moment there is a `lock` in code to prevent parallel queries from different sensors which means sensor queries are queued and there is only one active query. Probably this "queueing" causes the performance problem (I haven't checked deeper yet it is just a guess). 

I added logs to update of sensors and it is not called when entities are disabled so modbus variable not polled in that case.

**Comment by laszlojakab** [comment]
Hello Yanik, can you try something? There are 2 `with self._lock:` lines in threadsafe_controller.py. Could you remove them (and unindent the lines under with statement)? Probably some of your sensor could be broken after that but can you check if your HA is faster with this modification? I tried it on my RPI3 but I'm not sure if it is faster or not. As I wrote earlier I only noticed a small performance problem not a 'drastical' as you mentioned.

**Comment by laszlojakab** [comment]
@kickouille could you please test performance with  https://github.com/laszlojakab/homeassistant-easycontrols/tree/fix/network-stack-restart branch?

**Comment by kickouille** [comment]
Hi @laszlojakab,

Well I can clearly see an improvement, I am not able to notice any performance difference when your integration runs or not.

Great job!

Regarding the initial request, you said that the polling interval is set to the default 30 seconds.

I never put my handy into HA custom integrations, but do you think there is a way to override this default value?

Thank you!

**Comment by laszlojakab** [comment]
Hi @kickouille!

Thank you for your feedback. The performance problem related to issue #46. The fix for that issue will solve the performance problem too. I don't know any way to control polling interval for integrations which are set up from the UI. For configuration.yaml based sensors you can use scan_interval to set polling interval: 

https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval

As I wrote earlier you can disable unnecessary entities and configure recorder to log less into database. I think that's the way to solve your orignal problem.
